# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Dec 28 16:34:51 2020
# ------------------------------------------------

package:
    name: jupyterlab_widgets
    version: 1.0.0
source:
    sha256: 5c1a29a84d3069208cb506b10609175b249b6486d6b1cbae8fcde2a11584fb78
    url: https://pypi.io/packages/source/j/jupyterlab_widgets/jupyterlab_widgets-1.0.0.tar.gz
build:
    noarch: python
    number: '1'
    script: /home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1609173350931/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
        -m pip install . -vv
    string: pyhd8ed1ab_1
requirements:
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.12.5 ha878542_0
        - certifi 2020.12.5 py39hf3d152e_0
        - jupyter-packaging 0.7.9 pyhd8ed1ab_0
        - ld_impl_linux-64 2.35.1 hea4e1c9_1
        - libffi 3.3 h58526e2_2
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - ncurses 6.2 h58526e2_4
        - openssl 1.1.1i h7f98852_0
        - pip 20.3.3 pyhd8ed1ab_0
        - python 3.9.1 hffdb5ce_2_cpython
        - python_abi 3.9 1_cp39
        - readline 8.0 he28a2e2_2
        - setuptools 49.6.0 py39h079e4ff_2
        - sqlite 3.34.0 h74cdb3f_0
        - tk 8.6.10 h21135ba_1
        - tzdata 2020e he74cb21_0
        - wheel 0.36.2 pyhd3deb0d_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1010
    run:
        - python >=3.6
test:
    commands:
        - pip check
    imports:
        - jupyterlab_widgets
    requires:
        - pip
about:
    home: https://github.com/jupyter-widgets/ipywidgets
    license: BSD-3-Clause
    license_file: LICENSE
    summary: JupyterLab extension providing HTML widgets
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - SylvainCorlay
        - jasongrout
        - jtpio
