# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Apr 20 16:17:55 2021
# ------------------------------------------------

package:
  name: matplotlib-inline
  version: 0.1.2
source:
  sha256: f41d5ff73c9f5385775d5c0bc13b424535c8402fe70ea8210f93e11f3683993e
  url: https://pypi.io/packages/source/m/matplotlib-inline/matplotlib-inline-0.1.2.tar.gz
build:
  noarch: python
  number: '2'
  script: /home/conda/feedstock_root/build_artifacts/matplotlib-inline_1618935594181/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_2
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2020.12.5 ha878542_0
    - certifi 2020.12.5 py39hf3d152e_1
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - libstdcxx-ng 9.3.0 h6de172a_19
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - pip 21.0.1 pyhd8ed1ab_0
    - python 3.9.2 hffdb5ce_0_cpython
    - python_abi 3.9 1_cp39
    - readline 8.1 h46c0cb4_0
    - setuptools 49.6.0 py39hf3d152e_3
    - sqlite 3.35.4 h74cdb3f_0
    - tk 8.6.10 h21135ba_1
    - tzdata 2021a he74cb21_0
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - python >=3.6
    - traitlets
test:
  commands:
    - pip check
  imports:
    - matplotlib_inline
    - matplotlib_inline.backend_inline
  requires:
    - ipython
    - matplotlib-base
    - pip
about:
  dev_url: https://github.com/ipython/matplotlib-inline
  home: https://github.com/ipython/matplotlib-inline
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Inline Matplotlib backend for Jupyter
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - Carreau
    - SylvainCorlay
    - martinRenou
