# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: libgfortran-ng
  version: 11.1.0
source:
  - patches:
      - patches/0021-Hardcode-HAVE_ALIGNED_ALLOC-1-in-libstdc-v3-configur.patch
    url: https://ftp.gnu.org/gnu/gcc/gcc-11.1.0/gcc-11.1.0.tar.gz
build:
  number: 8
  string: h69a702a_8
requirements:
  build: []
  run:
    - libgfortran5 11.1.0 h6c583b3_8
test:
  commands:
    - test -f ${PREFIX}/lib/libgfortran.so
about:
  home: https://gcc.gnu.org/
  license: GPL-3.0-only WITH GCC-exception-3.1
  summary: The GNU Fortran Runtime Library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - beckermr
    - isuruf
