# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Dec  1 11:49:24 2020
# ------------------------------------------------

package:
    name: libopus
    version: 1.3.1
source:
    patches:
        - cmake_use_packageversion.patch
    sha256: 4834a8944c33a7ecab5cad9454eeabe4680ca1842cb8f5a2437572dbf636de8f
    url: https://github.com/xiph/opus/archive/v1.3.1.tar.gz
build:
    number: '1'
    run_exports:
        - libopus >=1.3.1,<2.0a0
    string: h7f98852_1
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - autoconf 2.69 pl5320h36c2ea0_10
        - automake 1.16.2 pl5320ha770c72_3
        - binutils_impl_linux-64 2.35.1 h17ad2fc_0
        - binutils_linux-64 2.35 hc3fd857_29
        - gcc_impl_linux-64 9.3.0 h28f5a38_17
        - gcc_linux-64 9.3.0 h7247604_29
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.35.1 hed1e6ac_0
        - libgcc-devel_linux-64 9.3.0 hfd08b2a_17
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - libtool 2.4.6 h58526e2_1007
        - m4 1.4.18 h516909a_1001
        - make 4.3 hd18ef5c_1
        - perl 5.32.0 h36c2ea0_0
        - sysroot_linux-64 2.12 h77966d4_13
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
    run:
        - libgcc-ng >=9.3.0
test:
    commands:
        - test -f ${PREFIX}/lib/libopus${SHLIB_EXT}
about:
    description: 'Opus is a totally open, royalty-free, highly versatile

        audio codec. Opus is unmatched for interactive speech

        and music transmission over the Internet, but is also

        intended for storage and streaming applications. It is

        standardized by the Internet Engineering Task Force

        (IETF) as RFC 6716 which incorporated technology from

        Skype''s SILK codec and Xiph.Org''s CELT codec.

        '
    dev_url: http://opus-codec.org/development/
    doc_url: http://opus-codec.org/docs/
    home: http://opus-codec.org/
    license: BSD-3-Clause
    license_file: COPYING
    summary: Opus Interactive Audio Codec
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - wolfv
