# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Aug 25 15:04:43 2021
# ------------------------------------------------

package:
  name: prompt-toolkit
  version: 3.0.20
source:
  sha256: eb71d5a6b72ce6db177af4a7d4d7085b99756bf656d98ffcc4fecd36850eea6c
  url: https://pypi.io/packages/source/p/prompt_toolkit/prompt_toolkit-3.0.20.tar.gz
build:
  noarch: python
  number: '0'
  string: pyha770c72_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.5.30 ha878542_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 11.1.0 hc902ee8_8
    - libgomp 11.1.0 hc902ee8_8
    - libstdcxx-ng 11.1.0 h56837e0_8
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_1
    - pip 21.2.4 pyhd8ed1ab_0
    - python 3.9.6 h49503c6_1_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 h46c0cb4_0
    - setuptools 57.4.0 py39hf3d152e_0
    - sqlite 3.36.0 h9cd32fc_0
    - tk 8.6.11 h21135ba_0
    - tzdata 2021a he74cb21_1
    - wheel 0.37.0 pyhd8ed1ab_1
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - python >=3.6
    - wcwidth
  run_constrained:
    - prompt_toolkit 3.0.20
about:
  description: 'prompt_toolkit is a library for building powerful interactive command

    lines and terminal applications in Python. It can be a pure Python

    replacement for GNU readline, but it can be much more than that.

    '
  dev_url: https://github.com/jonathanslenders/python-prompt-toolkit
  doc_url: http://python-prompt-toolkit.readthedocs.io
  home: https://github.com/jonathanslenders/python-prompt-toolkit
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Library for building powerful interactive command lines in Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - asmeurer
    - jakirkham
    - ocefpaf
    - scopatz
