# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Apr  2 17:04:56 2021
# ------------------------------------------------

package:
  name: nbformat
  version: 5.1.3
source:
  sha256: b516788ad70771c6250977c1374fcca6edebe6126fd2adb5a69aa5c2356fd1c8
  url: https://pypi.io/packages/source/n/nbformat/nbformat-5.1.3.tar.gz
build:
  entry_points:
    - jupyter-trust = nbformat.sign:TrustNotebookApp.launch_instance
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/nbformat_1617383142101/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2020.12.5 ha878542_0
    - certifi 2020.12.5 py39hf3d152e_1
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgomp 9.3.0 h2828fa1_18
    - libstdcxx-ng 9.3.0 h6de172a_18
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - pip 21.0.1 pyhd8ed1ab_0
    - python 3.9.2 hffdb5ce_0_cpython
    - python_abi 3.9 1_cp39
    - readline 8.0 he28a2e2_2
    - setuptools 49.6.0 py39hf3d152e_3
    - sqlite 3.35.3 h74cdb3f_0
    - tk 8.6.10 h21135ba_1
    - tzdata 2021a he74cb21_0
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - ipython_genutils
    - jsonschema >=2.4,!=2.5.0
    - jupyter_core
    - python >=3.5
    - traitlets >=4.1
test:
  commands:
    - pip check
    - jupyter-trust -h
    - pytest -vv --pyargs nbformat --cov nbformat --no-cov-on-fail --cov-fail-under
      "70" -k "not (upgrade_v4_to_4_dot_5 or sample_notebook)"
  imports:
    - nbformat
  requires:
    - pip
    - pytest
    - pytest-cov
    - python-fastjsonschema
    - testpath
about:
  dev_url: https://github.com/jupyter/nbformat
  doc_url: https://nbformat.readthedocs.io
  home: https://jupyter.org
  license: BSD-3-Clause
  license_file: COPYING.md
  summary: The Jupyter Notebook format
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - bollwyvl
    - jakirkham
    - minrk
    - mpacer
    - ocefpaf
    - pelson
    - takluyver
