# This file created by conda-build 3.21.3
# ------------------------------------------------

package:
  name: pyqt-impl
  version: 5.12.3
source:
  - folder: pyqt5
    patches:
      - 0003-configure.patch
      - py2_segfault.diff
      - qt5_dll.diff
    sha1: f442a876794947a24474cf85eb02abd60f00f642
    url: https://distfiles.macports.org/py-pyqt5/PyQt5_gpl-5.12.3.tar.gz
  - folder: sip
    patches:
      - 0001-Do-not-override-CC-CXX-LINK-in-sipgen-Makefile.patch
      - sip-get_config_h_filename.patch
    sha1: d001eb00f6dae26a952770e805b1519f61cae77d
    url: https://distfiles.macports.org/py-sip/sip-4.19.18.tar.gz
  - folder: pyqtwebengine
    sha1: 737acf93ecf39e5e2136e094a8b0a9ffa47bd2de
    url: https://distfiles.macports.org/py-pyqt5/PyQtWebEngine_gpl-5.12.1.tar.gz
  - folder: pyqtcharts
    sha1: 6a876ac37d0ccb5392f67669de5e790c8f9188da
    url: https://github.com/ocefpaf/pyqt-feedstock/releases/download/v5.12.3/PyQtChart_gpl-5.12.tar.gz
build:
  noarch: false
  noarch_python: false
  number: '7'
  script: build-pyqt.sh
  string: py38h7400c14_7
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - alsa-lib-cos6-x86_64 1.1.0 h9d98e8f_1104
    - alsa-lib-devel-cos6-x86_64 1.1.0 h9d98e8f_1104
    - atk-cos6-x86_64 1.30.0 h9d98e8f_1104
    - atk-devel-cos6-x86_64 1.30.0 h9d98e8f_1104
    - binutils_impl_linux-64 2.35.1 h193b22a_1
    - binutils_linux-64 2.35 hc3fd857_29
    - cairo-cos6-x86_64 1.8.8 h9d98e8f_1104
    - cairo-devel-cos6-x86_64 1.8.8 h9d98e8f_1104
    - fontconfig-cos6-x86_64 2.8.0 h9d98e8f_1104
    - fontconfig-devel-cos6-x86_64 2.8.0 h9d98e8f_1104
    - freetype-cos6-x86_64 2.3.11 h9d98e8f_1104
    - freetype-devel-cos6-x86_64 2.3.11 h9d98e8f_1104
    - gcc_impl_linux-64 9.3.0 h28f5a38_17
    - gcc_linux-64 9.3.0 h7247604_29
    - gdk-pixbuf2-cos6-x86_64 2.24.1 h9d98e8f_1104
    - gdk-pixbuf2-devel-cos6-x86_64 2.24.1 h9d98e8f_1104
    - glib2-cos6-x86_64 2.28.8 h9d98e8f_1104
    - glib2-devel-cos6-x86_64 2.28.8 h9d98e8f_1104
    - gtk2-cos6-x86_64 2.24.23 h9d98e8f_1104
    - gtk2-devel-cos6-x86_64 2.24.23 h9d98e8f_1104
    - gtkmm24-cos6-x86_64 2.18.2 h9d98e8f_1104
    - gtkmm24-devel-cos6-x86_64 2.18.2 h9d98e8f_1104
    - gxx_impl_linux-64 9.3.0 h53cdd4c_17
    - gxx_linux-64 9.3.0 h0d07fa4_29
    - kernel-headers-cos6-x86_64 2.6.32 h9d98e8f_1104
    - kernel-headers_linux-64 2.6.32 h77966d4_13
    - ld_impl_linux-64 2.35.1 hea4e1c9_1
    - libdrm-cos6-x86_64 2.4.65 h9d98e8f_1104
    - libdrm-devel-cos6-x86_64 2.4.65 h9d98e8f_1104
    - libgcc-devel_linux-64 9.3.0 hfd08b2a_17
    - libgcc-ng 9.3.0 h5dbcf3e_17
    - libgomp 9.3.0 h5dbcf3e_17
    - libselinux-cos6-x86_64 2.0.94 h9d98e8f_1104
    - libselinux-devel-cos6-x86_64 2.0.94 h9d98e8f_1104
    - libsepol-cos6-x86_64 2.0.41 h9d98e8f_1104
    - libsepol-devel-cos6-x86_64 2.0.41 h9d98e8f_1104
    - libstdcxx-devel_linux-64 9.3.0 h4084dd6_17
    - libstdcxx-ng 9.3.0 h2ae2ef3_17
    - libthai-cos6-x86_64 0.1.12 h9d98e8f_1104
    - libx11-common-cos6-x86_64 1.6.4 h9d98e8f_1104
    - libx11-cos6-x86_64 1.6.4 h9d98e8f_1104
    - libx11-devel-cos6-x86_64 1.6.4 h9d98e8f_1104
    - libxau-cos6-x86_64 1.0.6 h9d98e8f_1104
    - libxau-devel-cos6-x86_64 1.0.6 h9d98e8f_1104
    - libxcb-cos6-x86_64 1.12 h9d98e8f_1104
    - libxcomposite-cos6-x86_64 0.4.3 h9d98e8f_1104
    - libxcomposite-devel-cos6-x86_64 0.4.3 h9d98e8f_1104
    - libxcursor-cos6-x86_64 1.1.14 h9d98e8f_1104
    - libxcursor-devel-cos6-x86_64 1.1.14 h9d98e8f_1104
    - libxdamage-cos6-x86_64 1.1.3 h9d98e8f_1104
    - libxext-cos6-x86_64 1.3.3 h9d98e8f_1104
    - libxext-devel-cos6-x86_64 1.3.3 h9d98e8f_1104
    - libxfixes-cos6-x86_64 5.0.3 h9d98e8f_1104
    - libxi-cos6-x86_64 1.7.8 h9d98e8f_1104
    - libxi-devel-cos6-x86_64 1.7.8 h9d98e8f_1104
    - libxrandr-cos6-x86_64 1.5.1 h9d98e8f_1104
    - libxrandr-devel-cos6-x86_64 1.5.1 h9d98e8f_1104
    - libxrender-cos6-x86_64 0.9.10 h9d98e8f_1104
    - libxrender-devel-cos6-x86_64 0.9.10 h9d98e8f_1104
    - libxscrnsaver-cos6-x86_64 1.2.2 h9d98e8f_1104
    - libxscrnsaver-devel-cos6-x86_64 1.2.2 h9d98e8f_1104
    - libxtst-cos6-x86_64 1.2.3 h9d98e8f_1104
    - libxtst-devel-cos6-x86_64 1.2.3 h9d98e8f_1104
    - libxxf86vm-cos6-x86_64 1.1.3 h9d98e8f_1104
    - mesa-dri-drivers-cos6-x86_64 11.0.7 h9d98e8f_1104
    - mesa-dri1-drivers-cos6-x86_64 7.11 h9d98e8f_1104
    - mesa-libegl-cos6-x86_64 11.0.7 h9d98e8f_1104
    - mesa-libegl-devel-cos6-x86_64 11.0.7 h9d98e8f_1104
    - mesa-libgbm-cos6-x86_64 11.0.7 h9d98e8f_1104
    - mesa-libgl-cos6-x86_64 11.0.7 h9d98e8f_1104
    - mesa-libgl-devel-cos6-x86_64 11.0.7 h9d98e8f_1104
    - pango-cos6-x86_64 1.28.1 h9d98e8f_1104
    - pango-devel-cos6-x86_64 1.28.1 h9d98e8f_1104
    - pciutils-devel-cos6-x86_64 3.1.10 h9d98e8f_1104
    - pciutils-libs-cos6-x86_64 3.1.10 h9d98e8f_1104
    - pixman-cos6-x86_64 0.32.8 h9d98e8f_1104
    - pixman-devel-cos6-x86_64 0.32.8 h9d98e8f_1104
    - pkg-config 0.29.2 h36c2ea0_1008
    - pkgconfig-cos6-x86_64 0.23 h9d98e8f_1104
    - sysroot_linux-64 2.12 h77966d4_13
    - xorg-x11-proto-devel-cos6-x86_64 7.7 h9d98e8f_1104
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2020.12.5 ha878542_0
    - dbus 1.13.6 hfdff14a_1
    - expat 2.2.9 he1b5a44_2
    - fontconfig 2.13.1 h736d332_1003
    - freetype 2.10.4 h7ca028e_0
    - gettext 0.19.8.1 h0b5b191_1005
    - glib 2.66.4 hcd2ae1e_1
    - gst-plugins-base 1.14.5 h0935bb2_2
    - gstreamer 1.18.2 h3560a44_1
    - icu 68.1 h58526e2_0
    - jpeg 9d h36c2ea0_0
    - kernel-headers_linux-64 2.6.32 h77966d4_13
    - krb5 1.17.2 h926e7f8_0
    - ld_impl_linux-64 2.35.1 hea4e1c9_1
    - libclang 11.0.0 default_ha5c780c_2
    - libdrm-cos6-x86_64 2.4.65 h9d98e8f_1104
    - libedit 3.1.20191231 he28a2e2_2
    - libevent 2.1.10 hcdb4288_3
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h5dbcf3e_17
    - libglib 2.66.4 h164308a_1
    - libgomp 9.3.0 h5dbcf3e_17
    - libiconv 1.16 h516909a_0
    - libllvm11 11.0.0 he513fc3_0
    - libpng 1.6.37 h21135ba_2
    - libpq 12.3 h255efa7_3
    - libstdcxx-ng 9.3.0 h2ae2ef3_17
    - libuuid 2.32.1 h7f98852_1000
    - libx11-common-cos6-x86_64 1.6.4 h9d98e8f_1104
    - libx11-cos6-x86_64 1.6.4 h9d98e8f_1104
    - libxcb 1.13 h7f98852_1003
    - libxkbcommon 1.0.3 he3ba5ed_0
    - libxml2 2.9.10 h72842e0_3
    - lz4-c 1.9.3 h9c3ff4c_0
    - mesa-dri-drivers-cos6-x86_64 11.0.7 h9d98e8f_1104
    - mesa-dri1-drivers-cos6-x86_64 7.11 h9d98e8f_1104
    - mesa-libgl-cos6-x86_64 11.0.7 h9d98e8f_1104
    - mesa-libgl-devel-cos6-x86_64 11.0.7 h9d98e8f_1104
    - mysql-common 8.0.22 ha770c72_1
    - mysql-libs 8.0.22 h1fd7589_1
    - ncurses 6.2 h58526e2_4
    - nspr 4.29 h9c3ff4c_1
    - nss 3.60 hb5efdd6_0
    - openssl 1.1.1i h7f98852_0
    - pcre 8.44 he1b5a44_0
    - pthread-stubs 0.4 h36c2ea0_1001
    - pyqt5-sip 4.19.18 py38h709712a_7
    - python 3.8.6 hffdb5ce_4_cpython
    - qt 5.12.9 h9d6b050_2
    - readline 8.0 he28a2e2_2
    - sqlite 3.34.0 h74cdb3f_0
    - sysroot_linux-64 2.12 h77966d4_13
    - tk 8.6.10 h21135ba_1
    - xorg-libxau 1.0.9 h7f98852_0
    - xorg-libxdmcp 1.1.3 h7f98852_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
    - zstd 1.4.8 ha95c52a_1
  run:
    - dbus >=1.13.6,<2.0a0
    - libgcc-ng >=9.3.0
    - libstdcxx-ng >=9.3.0
    - pyqt5-sip 4.19.18 py38h709712a_7
    - python >=3.8,<3.9.0a0
    - python_abi 3.8.* *_cp38
    - qt >=5.12.9,<5.13.0a0
test:
  commands:
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'python pyqt_test.py'
    - pyuic5 --version
  files:
    - pyqt_test.py
  imports:
    - PyQt5.QtCore
    - PyQt5.QtGui
    - PyQt5.QtHelp
    - PyQt5.QtMultimedia
    - PyQt5.QtMultimediaWidgets
    - PyQt5.QtNetwork
    - PyQt5.QtOpenGL
    - PyQt5.QtPrintSupport
    - PyQt5.QtQml
    - PyQt5.QtQuick
    - PyQt5.QtSvg
    - PyQt5.QtTest
    - PyQt5.QtWebChannel
    - PyQt5.QtWebSockets
    - PyQt5.QtWidgets
    - PyQt5.QtXml
    - PyQt5.QtXmlPatterns
    - PyQt5.sip
about:
  description: '"PyQt is a set of Python v2 and v3 bindings for The Qt Company''s
    Qt

    application framework and runs on all platforms supported by Qt including

    Windows, MacOS/X and Linux. PyQt5 supports Qt v5. PyQt4 supports Qt v4 and

    will build against Qt v5. The bindings are implemented as a set of Python

    modules and contain over 1,000 classes."

    '
  dev_url: https://github.com/pyqt
  doc_url: https://www.riverbankcomputing.com/software/pyqt/
  home: http://www.riverbankcomputing.co.uk/software/pyqt
  license: LicenseRef-Commercial or GPL-2.0-only or GPL-3.0-only
  license_family: GPL
  license_file: pyqt5/LICENSE
  summary: Python binding of the cross-platform GUI toolkit Qt.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ccordoba12
    - gillins
    - jschueller
    - mingwandroid
    - msarahan
    - ocefpaf
