# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jul 15 17:45:16 2021
# ------------------------------------------------

package:
  name: charset-normalizer
  version: 2.0.0
source:
  sha256: 878bfe99324a9f3191e9a0f555e52ca2e0e1ad14b69802bc3f9a7afc71ffcfa4
  url: https://pypi.io/packages/source/c/charset-normalizer/charset-normalizer-2.0.0.tar.gz
build:
  entry_points:
    - normalizer = charset_normalizer.cli.normalizer:cli_detect
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/charset-normalizer_1626371162869/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.5.30 ha878542_0
    - certifi 2021.5.30 py39hf3d152e_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_1
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - libstdcxx-ng 9.3.0 h6de172a_19
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - pip 21.1.3 pyhd8ed1ab_0
    - python 3.9.6 h49503c6_1_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 h46c0cb4_0
    - setuptools 49.6.0 py39hf3d152e_3
    - sqlite 3.36.0 h9cd32fc_0
    - tk 8.6.10 h21135ba_1
    - tzdata 2021a he74cb21_1
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - python >=3.5
test:
  commands:
    - pip check
    - normalizer --help
  imports:
    - charset_normalizer
    - charset_normalizer.assets
  requires:
    - pip
about:
  home: https://github.com/ousret/charset_normalizer
  license: MIT
  license_file: LICENSE
  summary: The Real First Universal Charset Detector. Open, modern and actively maintained
    alternative to Chardet.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
