# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Aug 11 13:54:08 2021
# ------------------------------------------------

package:
  name: notebook
  version: 6.4.3
source:
  sha256: e6b6dfed36b00cf950f63c0d42e947c101d4258aec21624de62b9e0c11ed5c0d
  url: https://pypi.io/packages/source/n/notebook/notebook-6.4.3.tar.gz
build:
  entry_points:
    - jupyter-bundlerextension = notebook.bundler.bundlerextensions:main
    - jupyter-nbextension = notebook.nbextensions:main
    - jupyter-notebook = notebook.notebookapp:main
    - jupyter-serverextension = notebook.serverextensions:main
  noarch: python
  number: '0'
  script:
    - /home/conda/feedstock_root/build_artifacts/notebook_1628690102344/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
      -m pip install . --no-deps -vv
    - find /home/conda/feedstock_root/build_artifacts/notebook_1628690102344/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
      -name '*.js.map' -delete
  string: pyha770c72_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.5.30 ha878542_0
    - certifi 2021.5.30 py39hf3d152e_0
    - deprecation 2.1.0 pyh9f0ad1d_0
    - jupyter-packaging 0.10.4 pyhd8ed1ab_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 11.1.0 hc902ee8_8
    - libgomp 11.1.0 hc902ee8_8
    - libstdcxx-ng 11.1.0 h56837e0_8
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - packaging 21.0 pyhd8ed1ab_0
    - pip 21.2.3 pyhd8ed1ab_0
    - pyparsing 2.4.7 pyh9f0ad1d_0
    - python 3.9.6 h49503c6_1_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 h46c0cb4_0
    - setuptools 49.6.0 py39hf3d152e_3
    - sqlite 3.36.0 h9cd32fc_0
    - tk 8.6.10 h21135ba_1
    - tomlkit 0.7.2 py39hf3d152e_0
    - tzdata 2021a he74cb21_1
    - wheel 0.37.0 pyhd8ed1ab_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - argon2-cffi
    - ipykernel
    - ipython_genutils
    - jinja2
    - jupyter_client >=5.3.4
    - jupyter_core >=4.6.1
    - nbconvert
    - nbformat
    - prometheus_client
    - python >=3.7
    - pyzmq >=17
    - send2trash >=1.5.0
    - terminado >=0.8.3
    - tornado >=6.1
    - traitlets >=4.2.1
test:
  commands:
    - python -m pip check
    - jupyter notebook -h
    - jupyter nbextension -h
    - jupyter serverextension -h
    - jupyter bundlerextension -h
  imports:
    - notebook
    - notebook.tests.launchnotebook
  requires:
    - pip
    - requests
    - requests-unixsocket
about:
  dev_url: https://github.com/jupyter/notebook
  doc_source_url: https://github.com/jupyter/notebook/tree/master/docs
  doc_url: https://jupyter-notebook.readthedocs.io
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A web-based notebook environment for interactive computing
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - SylvainCorlay
    - blink1073
    - bollwyvl
    - davidbrochart
    - gnestor
    - jakirkham
    - lresende
    - minrk
    - pelson
    - takluyver
