# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Aug 26 08:31:28 2021
# ------------------------------------------------

package:
  name: zeromq
  version: 4.3.4
source:
  fn: zeromq-4.3.4.tar.gz
  patches:
    - 001-windows-install.patch
    - pr-4242.patch
  sha256: c593001a89f5a85dd2ddf564805deb860e02471171b3f204944857336295c3e5
  url: https://github.com/zeromq/libzmq/releases/download/v4.3.4/zeromq-4.3.4.tar.gz
build:
  number: '1'
  run_exports:
    - zeromq >=4.3.4,<4.4.0a0
  string: h9c3ff4c_1
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - autoconf 2.69 pl5320h36c2ea0_10
    - automake 1.16.2 pl5320ha770c72_3
    - binutils_impl_linux-64 2.36.1 h193b22a_2
    - binutils_linux-64 2.36 hf3e587d_0
    - gcc_impl_linux-64 9.4.0 h03d3576_8
    - gcc_linux-64 9.4.0 h391b98a_0
    - gxx_impl_linux-64 9.4.0 h03d3576_8
    - gxx_linux-64 9.4.0 h0316aca_0
    - kernel-headers_linux-64 2.6.32 he073ed8_14
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libgcc-devel_linux-64 9.4.0 hd854feb_8
    - libgcc-ng 11.1.0 hc902ee8_8
    - libgomp 11.1.0 hc902ee8_8
    - libsanitizer 9.4.0 h79bfe98_8
    - libstdcxx-devel_linux-64 9.4.0 hd854feb_8
    - libstdcxx-ng 11.1.0 h56837e0_8
    - libtool 2.4.6 h58526e2_1007
    - m4 1.4.18 h516909a_1001
    - make 4.3 hd18ef5c_1
    - perl 5.32.1 0_h7f98852_perl5
    - pkg-config 0.29.2 h36c2ea0_1008
    - sysroot_linux-64 2.12 he073ed8_14
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - libgcc-ng 11.1.0 hc902ee8_8
    - libgomp 11.1.0 hc902ee8_8
    - libsodium 1.0.18 h36c2ea0_1
    - libstdcxx-ng 11.1.0 h56837e0_8
  run:
    - libgcc-ng >=9.4.0
    - libsodium >=1.0.18,<1.0.19.0a0
    - libsodium >=1.0.18,<1.0.19.0a0
    - libstdcxx-ng >=9.4.0
about:
  home: http://zeromq.org
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: A high-performance asynchronous messaging library.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - JohanMabille
    - SylvainCorlay
    - davidbrochart
    - jakirkham
    - minrk
