# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu May 20 13:42:38 2021
# ------------------------------------------------

package:
  name: werkzeug
  version: 2.0.1
source:
  sha256: 1de1db30d010ff1af14a009224ec49ab2329ad2cde454c8a708130642d579c42
  url: https://pypi.io/packages/source/W/Werkzeug/Werkzeug-2.0.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/werkzeug_1621518206714/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2020.12.5 ha878542_0
    - certifi 2020.12.5 py39hf3d152e_1
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - libstdcxx-ng 9.3.0 h6de172a_19
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - pip 21.1.1 pyhd8ed1ab_0
    - python 3.9.4 hffdb5ce_0_cpython
    - python_abi 3.9 1_cp39
    - readline 8.1 h46c0cb4_0
    - setuptools 49.6.0 py39hf3d152e_3
    - sqlite 3.35.5 h74cdb3f_0
    - tk 8.6.10 h21135ba_1
    - tzdata 2021a he74cb21_0
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - dataclasses
    - python >=3.6
test:
  commands:
    - pip check
  imports:
    - werkzeug
    - werkzeug.debug
  requires:
    - pip
about:
  description: 'Werkzeug is a WSGI utility library for Python. It''s widely used and
    BSD licensed.

    '
  dev_url: https://github.com/pallets/werkzeug
  doc_url: https://werkzeug.palletsprojects.com/
  home: https://palletsprojects.com/p/werkzeug/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: The comprehensive WSGI web application library.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - goanpeca
    - mcs07
