# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: libpq
  version: '13.3'
source:
  patches:
    - patches/0001-fix-win-zlib-name.patch
    - patches/0002-disable-new-dtags.patch
    - patches/0004-fix-windows-openssl-links-for-openssl-1.1.1.patch
  sha256: 3cd9454fa8c7a6255b6743b767700925ead1b9ab0d7a0f9dcb1151010f8eb4a1
  url: https://ftp.postgresql.org/pub/source/v13.3/postgresql-13.3.tar.bz2
build:
  number: 0
  run_exports:
    - libpq >=13.3,<14.0a0
  string: hd57d9b9_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - binutils_impl_linux-64 2.35.1 h193b22a_2
    - binutils_linux-64 2.35 h67ddf6f_30
    - gcc_impl_linux-64 9.3.0 h70c0ae5_19
    - gcc_linux-64 9.3.0 hf25ea35_30
    - kernel-headers_linux-64 2.6.32 h77966d4_13
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libgcc-devel_linux-64 9.3.0 h7864c58_19
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - libstdcxx-ng 9.3.0 h6de172a_19
    - make 4.3 hd18ef5c_1
    - sysroot_linux-64 2.12 h77966d4_13
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2020.12.5 ha878542_0
    - krb5 1.19.1 hcc1bbae_0
    - libedit 3.1.20191231 he28a2e2_2
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - libstdcxx-ng 9.3.0 h6de172a_19
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - readline 8.1 h46c0cb4_0
    - tk 8.6.10 h21135ba_1
    - tzcode 2021a h7f98852_1
    - tzdata 2021a he74cb21_0
    - zlib 1.2.11 h516909a_1010
  run:
    - krb5 >=1.19.1,<1.20.0a0
    - libgcc-ng >=9.3.0
    - openssl >=1.1.1k,<1.1.2a
    - readline >=8.1,<9.0a0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - pg_config
    - test -f $PREFIX/lib/libpq.so.5.13
    - test -f $PREFIX/lib/libpq.so.5
    - test -f $PREFIX/lib/libpq.so
about:
  summary: The postgres runtime libraries and utilities (not the server itself)
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - gillins
    - mariusvniekerk
    - msarahan
    - ocefpaf
    - sodre
