# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sun May 30 18:24:41 2021
# ------------------------------------------------

package:
  name: ca-certificates
  version: 2021.5.30
source:
  sha256: 2bbf76fd432960138b3ef6dda3dde0544f27cbf8546c458e60baf371917ba9ee
  url: https://pypi.io/packages/source/c/certifi/certifi-2021.5.30.tar.gz
build:
  number: '0'
  string: ha878542_0
requirements:
  build: []
  run: []
test:
  commands:
    - test -f "${PREFIX}/ssl/cacert.pem"
    - test -f "${PREFIX}/ssl/cert.pem"
    - curl --cacert "${PREFIX}/ssl/cacert.pem" https://www.google.com
  requires:
    - curl
about:
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: ISC
  license_file: LICENSE
  summary: Certificates for use with other packages.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
