# This file created by conda-build 3.12.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Aug  1 09:08:30 2018
# ------------------------------------------------

package:
    name: async_generator
    version: '1.10'
source:
    sha256: 6ebb3d106c12920aaae42ccb6f787ef5eefdcdd166ea3d628fa8476abe712144
    url: https://pypi.io/packages/source/a/async_generator/async_generator-1.10.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    build:
        - bzip2 1.0.6 h470a237_2
        - ca-certificates 2018.4.16 0
        - certifi 2018.4.16 py37_0
        - libffi 3.2.1 3
        - libgcc-ng 7.2.0 hdf63c60_3
        - libstdcxx-ng 7.2.0 hdf63c60_3
        - ncurses 6.1 hfc679d8_1
        - openssl 1.0.2o h470a237_1
        - pip 18.0 py37_0
        - python 3.7.0 h5001a0f_0
        - readline 7.0 haf1bffa_1
        - setuptools 40.0.0 py37_1
        - sqlite 3.24.0 h2f33b56_0
        - tk 8.6.8 0
        - wheel 0.31.1 py37_1
        - xz 5.2.4 h470a237_0
        - zlib 1.2.11 h470a237_3
    run:
        - python >2.7
test:
    imports:
        - async_generator
        - async_generator._tests
about:
    description: Python 3.6 added async generators, Python 3.7 adds some more tools
        to make them usable, like contextlib.asynccontextmanager. This library gives
        you all that back to Python 3.5.
    dev_url: https://github.com/python-trio/async_generator
    home: https://github.com/python-trio/async_generator
    license: MIT
    license_family: MIT
    summary: Async generators and context managers for Python 3.5+
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - nicoddemus
