# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Sat Aug 28 18:01:05 2021
# ------------------------------------------------

package:
  name: kiwisolver
  version: 1.3.2
source:
  sha256: fc4453705b81d03568d5b808ad8f09c77c47534f6ac2e72e733f9ca4714aa75c
  url: https://pypi.io/packages/source/k/kiwisolver/kiwisolver-1.3.2.tar.gz
build:
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/kiwisolver_1630173724167/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . -vv
  string: py38h1fd1430_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - binutils_impl_linux-64 2.36.1 h193b22a_2
    - binutils_linux-64 2.36 hf3e587d_0
    - gcc_impl_linux-64 9.4.0 h03d3576_8
    - gcc_linux-64 9.4.0 h391b98a_0
    - gxx_impl_linux-64 9.4.0 h03d3576_8
    - gxx_linux-64 9.4.0 h0316aca_0
    - kernel-headers_linux-64 2.6.32 he073ed8_14
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libgcc-devel_linux-64 9.4.0 hd854feb_8
    - libgcc-ng 11.1.0 hc902ee8_8
    - libgomp 11.1.0 hc902ee8_8
    - libsanitizer 9.4.0 h79bfe98_8
    - libstdcxx-devel_linux-64 9.4.0 hd854feb_8
    - libstdcxx-ng 11.1.0 h56837e0_8
    - sysroot_linux-64 2.12 he073ed8_14
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.5.30 ha878542_0
    - cppy 1.1.0 pyh9f0ad1d_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 11.1.0 hc902ee8_8
    - libgomp 11.1.0 hc902ee8_8
    - libstdcxx-ng 11.1.0 h56837e0_8
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_1
    - pip 21.2.4 pyhd8ed1ab_0
    - python 3.8.10 h49503c6_1_cpython
    - python_abi 3.8 2_cp38
    - readline 8.1 h46c0cb4_0
    - setuptools 57.4.0 py38h578d9bd_0
    - sqlite 3.36.0 h9cd32fc_0
    - tk 8.6.11 h21135ba_0
    - wheel 0.37.0 pyhd8ed1ab_1
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - libgcc-ng >=9.4.0
    - libstdcxx-ng >=9.4.0
    - python >=3.8,<3.9.0a0
    - python_abi 3.8.* *_cp38
test:
  commands:
    - pip check
  imports:
    - kiwisolver
  requires:
    - pip
about:
  home: https://github.com/nucleic/kiwi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A fast implementation of the Cassowary constraint solver
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - MatthieuDartiailh
    - blink1073
    - licode
    - ocefpaf
    - sccolbert
    - tacaswell
