# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Jul 12 11:42:53 2021
# ------------------------------------------------

package:
  name: tenacity
  version: 8.0.1
source:
  fn: tenacity-8.0.1.tar.gz
  sha256: 43242a20e3e73291a28bcbcacfd6e000b02d3857a9a9fff56b297a27afdc932f
  url: https://pypi.io/packages/source/t/tenacity/tenacity-8.0.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/tenacity_1626090218611/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install -vv .
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.5.30 ha878542_0
    - certifi 2021.5.30 py39hf3d152e_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_1
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - libstdcxx-ng 9.3.0 h6de172a_19
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - pip 21.1.3 pyhd8ed1ab_0
    - python 3.9.6 h49503c6_1_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 h46c0cb4_0
    - setuptools 49.6.0 py39hf3d152e_3
    - setuptools-scm 6.0.1 pyh44b312d_0
    - setuptools_scm 6.0.1 hd8ed1ab_0
    - sqlite 3.36.0 h9cd32fc_0
    - tk 8.6.10 h21135ba_1
    - toml 0.10.2 pyhd8ed1ab_0
    - tzdata 2021a he74cb21_1
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - python >=3.6
test:
  commands:
    - pip check
  imports:
    - tenacity
  requires:
    - pip
about:
  description: 'Tenacity is general-purpose retrying library, written in Python, to
    simplify the task of

    adding retry behavior to just about anything. It originates from a fork of Retrying

    '
  dev_url: http://github.com/jd/tenacity
  doc_url: http://tenacity.readthedocs.io
  home: http://github.com/jd/tenacity
  license: Apache-2.0
  license_file: LICENSE
  summary: Retry a flaky function whenever an exception occurs until it works
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - sodre
    - xylar
