# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Jun 30 03:28:03 2021
# ------------------------------------------------

package:
  name: qtconsole
  version: 5.1.1
source:
  sha256: bbc34bca14f65535afcb401bc74b752bac955e5313001ba640383f7e5857dc49
  url: https://pypi.io/packages/source/q/qtconsole/qtconsole-5.1.1.tar.gz
build:
  entry_points:
    - jupyter-qtconsole = qtconsole.qtconsoleapp:main
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/qtconsole_1625023841584/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.5.30 ha878542_0
    - certifi 2021.5.30 py39hf3d152e_0
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - libstdcxx-ng 9.3.0 h6de172a_19
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - pip 21.1.3 pyhd8ed1ab_0
    - python 3.9.5 h49503c6_0_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 h46c0cb4_0
    - setuptools 49.6.0 py39hf3d152e_3
    - sqlite 3.36.0 h9cd32fc_0
    - tk 8.6.10 h21135ba_1
    - tzdata 2021a he74cb21_0
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - ipykernel >=4.1
    - ipython_genutils
    - jupyter_client >=4.1
    - jupyter_core
    - pygments
    - pyqt
    - python >=3.6
    - qtpy
    - traitlets
test:
  commands:
    - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'jupyter qtconsole --help'
  imports:
    - qtconsole
    - qtconsole.tests
about:
  description: 'A rich Qt-based console for working with Jupyter kernels, supporting
    rich

    media output, session export, and more. The Qt console is a very

    lightweight application that largely feels like a terminal, but provides

    a number of enhancements only possible in a GUI, such as inline figures,

    proper multiline editing with syntax highlighting, graphical calltips, and

    more.

    '
  dev_url: https://github.com/jupyter/qtconsole
  doc_source_url: https://github.com/jupyter/qtconsole/tree/master/docs
  doc_url: https://qtconsole.readthedocs.org/en/stable/
  home: http://jupyter.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Jupyter Qt console
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - Carreau
    - ccordoba12
    - jakirkham
    - minrk
    - ocefpaf
    - takluyver
