# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Mon Aug 16 12:16:32 2021
# ------------------------------------------------

package:
  name: ipykernel
  version: 6.2.0
source:
  sha256: 4439459f171d77f35b7f7e72dace5d7c2dd10a5c9e2c22b173ad9048fbfe7656
  url: https://pypi.io/packages/source/i/ipykernel/ipykernel-6.2.0.tar.gz
build:
  number: '0'
  script:
    - /home/conda/feedstock_root/build_artifacts/ipykernel_1629116235985/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
      setup.py bdist_wheel
    - cd dist
    - /home/conda/feedstock_root/build_artifacts/ipykernel_1629116235985/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
      -m pip install ipykernel-6.2.0-py3-none-any.whl --no-deps -vv
    - /home/conda/feedstock_root/build_artifacts/ipykernel_1629116235985/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
      -m ipykernel install --sys-prefix
  string: py38he5a9106_0
requirements:
  build: []
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - backcall 0.2.0 pyh9f0ad1d_0
    - backports 1.0 py_2
    - backports.functools_lru_cache 1.6.4 pyhd8ed1ab_0
    - ca-certificates 2021.5.30 ha878542_0
    - certifi 2021.5.30 py38h578d9bd_0
    - debugpy 1.4.1 py38h709712a_0
    - decorator 5.0.9 pyhd8ed1ab_0
    - ipython 7.26.0 py38he5a9106_0
    - ipython_genutils 0.2.0 py_1
    - jedi 0.18.0 py38h578d9bd_2
    - jupyter_client 6.1.12 pyhd8ed1ab_0
    - jupyter_core 4.7.1 py38h578d9bd_0
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 11.1.0 hc902ee8_8
    - libgomp 11.1.0 hc902ee8_8
    - libsodium 1.0.18 h36c2ea0_1
    - libstdcxx-ng 11.1.0 h56837e0_8
    - matplotlib-inline 0.1.2 pyhd8ed1ab_2
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - parso 0.8.2 pyhd8ed1ab_0
    - pexpect 4.8.0 pyh9f0ad1d_2
    - pickleshare 0.7.5 py_1003
    - pip 21.2.4 pyhd8ed1ab_0
    - prompt-toolkit 3.0.19 pyha770c72_0
    - ptyprocess 0.7.0 pyhd3deb0d_0
    - pygments 2.9.0 pyhd8ed1ab_0
    - python 3.8.10 h49503c6_1_cpython
    - python-dateutil 2.8.2 pyhd8ed1ab_0
    - python_abi 3.8 2_cp38
    - pyzmq 22.2.1 py38h2035c66_0
    - readline 8.1 h46c0cb4_0
    - setuptools 49.6.0 py38h578d9bd_3
    - six 1.16.0 pyh6c4a22f_0
    - sqlite 3.36.0 h9cd32fc_0
    - tk 8.6.10 h21135ba_1
    - tornado 6.1 py38h497a2fe_1
    - traitlets 5.0.5 py_0
    - wcwidth 0.2.5 pyh9f0ad1d_2
    - wheel 0.37.0 pyhd8ed1ab_1
    - xz 5.2.5 h516909a_1
    - zeromq 4.3.4 h9c3ff4c_0
    - zlib 1.2.11 h516909a_1010
  run:
    - debugpy >=1,<2.0
    - ipython >=7.23.1,<8.0
    - jupyter_client <8.0
    - matplotlib-inline >=0.1.0,<0.2.0
    - python >=3.8,<3.9.0a0
    - python_abi 3.8.* *_cp38
    - tornado >=4.2,<7.0
    - traitlets >=4.1.0,<6.0
test:
  commands:
    - pip check
    - jupyter kernelspec list
  imports:
    - ipykernel
  requires:
    - curio
    - flaky
    - ipyparallel
    - matplotlib-base
    - nose
    - numpy
    - pip
    - pytest !=5.3.4
    - pytest-cov
    - pytest-timeout
    - trio
about:
  description: 'A powerful interactive Python shell and a Jupyter kernel to work with

    Python code in Jupyter notebooks and other interactive frontends.

    '
  dev_url: https://github.com/ipython/ipykernel
  doc_source_url: https://github.com/ipython/ipykernel/blob/master/docs/index.rst
  doc_url: https://ipython.readthedocs.io
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.md
  summary: IPython Kernel for Jupyter
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - Carreau
    - blink1073
    - bollwyvl
    - davidbrochart
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
