# This file created by conda-build 3.20.5
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Nov 24 16:38:52 2020
# ------------------------------------------------

package:
    name: libxkbcommon
    version: 1.0.3
source:
    sha256: 5d10a57ab65daad7d975926166770eca1d2c899131ab96c23845df1c42da5c31
    url: https://github.com/xkbcommon/libxkbcommon/archive/xkbcommon-1.0.3.tar.gz
build:
    missing_dso_whitelist:
        - /lib/libc.so.6
    number: '0'
    run_exports:
        - libxkbcommon >=1.0.3,<2.0a0
    string: he3ba5ed_0
requirements:
    build:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - binutils_impl_linux-64 2.35.1 h17ad2fc_0
        - binutils_linux-64 2.35 hc3fd857_29
        - bison 3.4 h58526e2_1
        - bzip2 1.0.8 h516909a_3
        - c-ares 1.17.1 h36c2ea0_0
        - ca-certificates 2020.11.8 ha878542_0
        - certifi 2020.11.8 py39hf3d152e_0
        - cmake 3.18.4 h1f3970d_0
        - expat 2.2.9 he1b5a44_2
        - flex 2.6.4 h58526e2_1004
        - gcc_impl_linux-64 7.5.0 hda68d29_13
        - gcc_linux-64 7.5.0 he2a3fca_29
        - gxx_impl_linux-64 7.5.0 h64c220c_13
        - gxx_linux-64 7.5.0 h547f3ba_29
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - krb5 1.17.2 h926e7f8_0
        - ld_impl_linux-64 2.35.1 hed1e6ac_0
        - libcurl 7.71.1 hcdd3856_8
        - libedit 3.1.20191231 he28a2e2_2
        - libev 4.33 h516909a_1
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libnghttp2 1.41.0 h8cfc5f6_2
        - libssh2 1.9.0 hab1572f_5
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - libuv 1.40.0 hd18ef5c_0
        - m4 1.4.18 h516909a_1001
        - meson 0.56.0 pyhd8ed1ab_0
        - ncurses 6.2 h58526e2_4
        - ninja 1.10.1 hfc4b9b4_2
        - openssl 1.1.1h h516909a_0
        - pkg-config 0.29.2 h36c2ea0_1008
        - python 3.9.0 h2a148a8_4_cpython
        - python_abi 3.9 1_cp39
        - readline 8.0 he28a2e2_2
        - rhash 1.3.6 h516909a_1001
        - setuptools 49.6.0 py39h079e4ff_2
        - sqlite 3.33.0 h4cf870e_1
        - sysroot_linux-64 2.12 h77966d4_13
        - tk 8.6.10 hed695b0_1
        - tzdata 2020d h516909a_0
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1010
    host:
        - _libgcc_mutex 0.1 conda_forge
        - _openmp_mutex 4.5 1_gnu
        - ca-certificates 2020.11.8 ha878542_0
        - icu 67.1 he1b5a44_0
        - kernel-headers_linux-64 2.6.32 h77966d4_13
        - ld_impl_linux-64 2.35.1 hed1e6ac_0
        - libffi 3.2.1 he1b5a44_1007
        - libgcc-ng 9.3.0 h5dbcf3e_17
        - libgomp 9.3.0 h5dbcf3e_17
        - libiconv 1.16 h516909a_0
        - libstdcxx-ng 9.3.0 h2ae2ef3_17
        - libxcb 1.13 h14c3975_1002
        - libxml2 2.9.10 h68273f3_2
        - ncurses 6.2 h58526e2_4
        - openssl 1.1.1h h516909a_0
        - pthread-stubs 0.4 h36c2ea0_1001
        - python 3.8.6 h852b56e_0_cpython
        - python_abi 3.8 1_cp38
        - readline 8.0 he28a2e2_2
        - sqlite 3.33.0 h4cf870e_1
        - sysroot_linux-64 2.12 h77966d4_13
        - tk 8.6.10 hed695b0_1
        - xcb-proto 1.13 py38h1e0a361_1003
        - xorg-libxau 1.0.9 h14c3975_0
        - xorg-libxdmcp 1.1.3 h516909a_0
        - xorg-x11-proto-devel-cos6-x86_64 7.7 h9d98e8f_1104
        - xorg-xproto 7.0.31 h14c3975_1007
        - xz 5.2.5 h516909a_1
        - zlib 1.2.11 h516909a_1010
    run:
        - libgcc-ng >=7.5.0
        - libstdcxx-ng >=7.5.0
        - libxml2 >=2.9.10,<2.10.0a0
test:
    commands:
        - test -f "${PREFIX}/lib/libxkbcommon${SHLIB_EXT}"
about:
    description: 'libxkbcommon is a keyboard keymap compiler and support library which

        processes a reduced subset of keymaps as defined by the XKB (X Keyboard

        Extension) specification.

        '
    dev_url: https://github.com/xkbcommon/libxkbcommon
    doc_url: https://xkbcommon.org/
    home: https://github.com/xkbcommon/libxkbcommon
    license: MIT/X11 Derivative
    license_family: MIT
    license_file: LICENSE
    summary: keymap handling library for toolkits and window systems
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - scopatz
