# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: libgcc-ng
  version: 11.1.0
source:
  - patches:
      - patches/0021-Hardcode-HAVE_ALIGNED_ALLOC-1-in-libstdc-v3-configur.patch
    url: https://ftp.gnu.org/gnu/gcc/gcc-11.1.0/gcc-11.1.0.tar.gz
build:
  binary_relocation: false
  detect_binary_files_with_prefix: false
  ignore_run_exports:
    - __glibc
  missing_dso_whitelist:
    - '*'
  number: 8
  rpaths_patcher: patchelf
  string: hc902ee8_8
requirements:
  build:
    - binutils_impl_linux-64 2.36.1 h193b22a_2
    - gcc_bootstrap_linux-64 11.1.0 ha7b995c_0
    - kernel-headers_linux-64 2.6.32 he073ed8_14
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - sysroot_linux-64 2.12 he073ed8_14
  host:
    - _openmp_mutex 4.5 1_gnu
    - kernel-headers_linux-64 2.6.32 he073ed8_14
    - libgomp 11.1.0 hc902ee8_8
    - sysroot_linux-64 2.12 he073ed8_14
  run:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex >=4.5
  run_constrained:
    - libgomp 11.1.0 hc902ee8_8
test:
  commands:
    - test -f ${PREFIX}/lib/libgcc_s.so
    - test -f ${PREFIX}/lib/libgomp.so.1
    - test `readlink ${PREFIX}/lib/libgomp.so.1` == "libgomp.so.1.0.0"
  requires:
    - sysroot_linux-64
about:
  home: https://gcc.gnu.org/onlinedocs/gccint/Libgcc.html
  license: GPL-3.0-only WITH GCC-exception-3.1
  summary: The GCC low-level runtime library
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - beckermr
    - isuruf
