# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: python
  version: 3.8.10
source:
  - md5: d9eee4b20155553830a2025e4dcaa7b3
    patches:
      - patches/0001-Fix-off-by-one-error-in-_winapi_WaitForMultipleObjec.patch
      - patches/0003-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
      - patches/0004-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0005-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
      - patches/0006-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - patches/0007-Support-cross-compiling-byte-code.patch
      - patches/0008-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
      - patches/0009-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
      - patches/0010-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0011-Win32-Do-not-download-externals.patch
      - patches/0012-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
      - patches/0013-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0014-Disable-new-dtags-in-unixccompiler.py.patch
      - patches/0015-Fix-cross-compilation-on-Debian-based-distros.patch
      - patches/0016-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0017-Unvendor-openssl.patch
      - patches/0018-Unvendor-sqlite3.patch
      - patches/0019-venv-Revert-a-change-from-https-github.com-python-cp.patch
      - patches/0020-Win-Add-back-the-DLLSuffix-used-to-find-the-openssl-.patch
      - patches/0021-Use-ranlib-from-env-if-env-variable-is-set.patch
      - patches/0022-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0023-Revert-part-of-https-bugs.python.org-issue33895-http.patch
      - patches/0024-cross-compile-darwin.patch.patch
      - patches/0032-ctypes-link-to-coreFoundation.patch
    url: https://www.python.org/ftp/python/3.8.10/Python-3.8.10.tar.xz
build:
  activate_in_script: true
  detect_binary_files_with_prefix: true
  ignore_run_exports:
    - bzip2
  no_link: null
  number: 1
  run_exports:
    noarch:
      - python
    weak:
      - python_abi 3.8.* *_cp38
  skip_compile_pyc: null
  string: h49503c6_1_cpython
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - binutils_impl_linux-64 2.35.1 h193b22a_2
    - binutils_linux-64 2.35 h67ddf6f_30
    - gcc_impl_linux-64 9.3.0 h70c0ae5_19
    - gcc_linux-64 9.3.0 hf25ea35_30
    - gxx_impl_linux-64 9.3.0 hd87eabc_19
    - gxx_linux-64 9.3.0 h3fbe746_30
    - kernel-headers_linux-64 2.6.32 h77966d4_13
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libgcc-devel_linux-64 9.3.0 h7864c58_19
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - libstdcxx-devel_linux-64 9.3.0 hb016644_19
    - libstdcxx-ng 9.3.0 h6de172a_19
    - libtool 2.4.6 h58526e2_1007
    - libuuid-cos6-x86_64 2.17.2 h9d98e8f_1104
    - libuuid-devel-cos6-x86_64 2.17.2 h9d98e8f_1104
    - libx11-common-cos6-x86_64 1.6.4 h9d98e8f_1104
    - libx11-cos6-x86_64 1.6.4 h9d98e8f_1104
    - libx11-devel-cos6-x86_64 1.6.4 h9d98e8f_1104
    - make 4.3 hd18ef5c_1
    - patch 2.7.6 h7f98852_1002
    - pkg-config 0.29.2 h36c2ea0_1008
    - sysroot_linux-64 2.12 h77966d4_13
    - xorg-x11-proto-devel-cos6-x86_64 7.7 h9d98e8f_1104
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7f98852_4
    - ca-certificates 2020.12.5 ha878542_0
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - libstdcxx-ng 9.3.0 h6de172a_19
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - readline 8.1 h46c0cb4_0
    - sqlite 3.35.5 h74cdb3f_0
    - tk 8.6.10 h21135ba_1
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - ld_impl_linux-64 >=2.34
    - libffi >=3.3,<3.4.0a0
    - libgcc-ng >=9.3.0
    - libstdcxx-ng >=9.3.0
    - ncurses >=6.2,<6.3.0a0
    - openssl >=1.1.1k,<1.1.2a
    - readline >=8.1,<9.0a0
    - sqlite >=3.35.5,<4.0a0
    - tk >=8.6.10,<8.7.0a0
    - xz >=5.2.5,<5.3.0a0
    - zlib >=1.2.11,<1.3.0a0
  run_constrained:
    - python_abi 3.8.* *_cp38
test:
  commands:
    - python -V
    - python3 -V
    - 2to3 -h
    - pydoc -h
    - python3-config --help
    - python -m venv test-venv
    - python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - _CONDA_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
      python -c "import sysconfig; print(sysconfig.get_config_var('CC'))"
    - for f in ${CONDA_PREFIX}/lib/python*/_sysconfig*.py; do echo "Checking $f:";
      if [[ `rg @ $f` ]]; then echo "FAILED ON $f"; cat $f; exit 1; fi; done
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.a
    - test ! -f ${PREFIX}/lib/libpython${PKG_VERSION%.*}.nolto.a
    - pushd tests
    - pushd distutils
    - python setup.py install -v -v
    - python -c "import foobar"
    - popd
    - pushd distutils.cext
    - python setup.py install -v -v
    - python -c "import greet; greet.greet('Python user')" | rg "Hello Python"
    - popd
    - pushd prefix-replacement
    - bash build-and-test.sh
    - popd
    - pushd cmake
    - cmake -GNinja -DPY_VER=3.8.10
    - popd
    - popd
  files:
    - tests/cmake/*
    - tests/cython/*
    - tests/distutils.cext/*
    - tests/distutils/*
    - tests/prefix-replacement/*
  requires:
    - cmake
    - cython
    - gcc_linux-64 9.*
    - gxx_linux-64 9.*
    - ninja
    - ripgrep
    - setuptools
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://docs.python.org/devguide/
  doc_source_url: https://github.com/python/pythondotorg/blob/master/docs/source/index.rst
  doc_url: https://www.python.org/doc/versions/
  home: https://www.python.org/
  license: Python-2.0
  license_file: LICENSE
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  feedstock-name: python
  final: true
  recipe-maintainers:
    - isuruf
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
