# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: libllvm11
  version: 11.1.0
source:
  patches:
    - patches/expect-fastmath-entrypoints-in-add-TLI-mappings.ll.patch
    - patches/intel-D47188-svml-VF.patch
    - patches/llvm-config-no-libLLVM.diff
    - patches/numba-0001-Revert-Limit-size-of-non-GlobalValue-name.patch
    - patches/pass-through-qemu-ld-prefix.diff
  sha256: ce8508e318a01a63d4e8b3090ab2ded3c598a50258cc49e2625b9120d4c03ea5
  url: https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/llvm-11.1.0.src.tar.xz
build:
  activate_in_script: true
  number: 2
  run_exports:
    - libllvm11 >=11.1.0,<11.2.0a0
  string: hf817b99_2
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - binutils_impl_linux-64 2.35.1 h193b22a_2
    - binutils_linux-64 2.35 h67ddf6f_30
    - bzip2 1.0.8 h7f98852_4
    - c-ares 1.17.1 h7f98852_1
    - ca-certificates 2020.12.5 ha878542_0
    - cmake 3.19.7 h3020d66_0
    - expat 2.3.0 h9c3ff4c_0
    - gcc_impl_linux-64 9.3.0 h70c0ae5_18
    - gcc_linux-64 9.3.0 hf25ea35_30
    - gxx_impl_linux-64 9.3.0 hd87eabc_18
    - gxx_linux-64 9.3.0 h3fbe746_30
    - kernel-headers_linux-64 2.6.32 h77966d4_13
    - krb5 1.17.2 h926e7f8_0
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libcurl 7.76.0 hc4aaa36_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 h516909a_1
    - libffi 3.3 h58526e2_2
    - libgcc-devel_linux-64 9.3.0 h7864c58_18
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgomp 9.3.0 h2828fa1_18
    - libnghttp2 1.43.0 h812cca2_0
    - libssh2 1.9.0 ha56f1ee_6
    - libstdcxx-devel_linux-64 9.3.0 hb016644_18
    - libstdcxx-ng 9.3.0 h6de172a_18
    - libuv 1.41.0 h7f98852_0
    - lz4-c 1.9.3 h9c3ff4c_0
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - python 3.9.2 hffdb5ce_0_cpython
    - readline 8.0 he28a2e2_2
    - rhash 1.4.1 h7f98852_0
    - sqlite 3.35.4 h74cdb3f_0
    - sysroot_linux-64 2.12 h77966d4_13
    - tk 8.6.10 h21135ba_1
    - tzdata 2021a he74cb21_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
    - zstd 1.4.9 ha95c52a_0
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgomp 9.3.0 h2828fa1_18
    - libstdcxx-ng 9.3.0 h6de172a_18
    - zlib 1.2.11 h516909a_1010
  run:
    - libgcc-ng >=9.3.0
    - libstdcxx-ng >=9.3.0
    - zlib >=1.2.11,<1.3.0a0
test:
  commands:
    - test -f $PREFIX/lib/libLLVM-11${SHLIB_EXT}
about:
  dev_url: https://github.com/llvm-mirror/llvm
  home: http://llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_family: Apache
  license_file: LICENSE.TXT
  summary: Development headers and libraries for LLVM
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - SylvainCorlay
    - inducer
    - isuruf
    - jakirkham
    - mingwandroid
    - timsnyder
