# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed May 19 10:10:26 2021
# ------------------------------------------------

package:
  name: jinja2
  version: 3.0.1
source:
  fn: Jinja2-3.0.1.tar.gz
  sha256: 703f484b47a6af502e743c9122595cc812b0271f661722403114f71a79d0f5a4
  url: https://pypi.io/packages/source/J/Jinja2/Jinja2-3.0.1.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/jinja2_1621419064915/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . --no-deps -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2020.12.5 ha878542_0
    - certifi 2020.12.5 py39hf3d152e_1
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - libstdcxx-ng 9.3.0 h6de172a_19
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - pip 21.1.1 pyhd8ed1ab_0
    - python 3.9.4 hffdb5ce_0_cpython
    - python_abi 3.9 1_cp39
    - readline 8.1 h46c0cb4_0
    - setuptools 49.6.0 py39hf3d152e_3
    - sqlite 3.35.5 h74cdb3f_0
    - tk 8.6.10 h21135ba_1
    - tzdata 2021a he74cb21_0
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - markupsafe >=2.0.0rc2
    - python >=3.6
test:
  commands:
    - pip check
  imports:
    - jinja2
  requires:
    - pip
about:
  description: 'Jinja2 is a full featured template engine for Python. It has full
    unicode

    support, an optional integrated sandboxed execution environment, widely

    used and BSD licensed.

    '
  dev_url: https://github.com/pallets/jinja
  doc_source_url: https://github.com/pallets/jinja/blob/master/docs/index.rst
  doc_url: http://jinja.pocoo.org/docs/dev/
  home: http://jinja.pocoo.org
  license: BSD-3-Clause
  license_file: LICENSE.rst
  summary: An easy to use stand-alone template engine written in pure python.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jakirkham
    - msarahan
    - nehaljwani
    - scopatz
