# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri May 21 20:44:27 2021
# ------------------------------------------------

package:
  name: flask
  version: 2.0.1
source:
  fn: Flask-2.0.1.tar.gz
  sha256: 1c4c257b1892aec1398784c63791cbaa43062f1f7aeb555c4da961b20ee68f55
  url: https://pypi.io/packages/source/F/Flask/Flask-2.0.1.tar.gz
build:
  entry_points:
    - flask = flask.cli:main
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/flask_1621629915293/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2020.12.5 ha878542_0
    - certifi 2020.12.5 py39hf3d152e_1
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - libstdcxx-ng 9.3.0 h6de172a_19
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - pip 21.1.1 pyhd8ed1ab_0
    - python 3.9.4 hffdb5ce_0_cpython
    - python_abi 3.9 1_cp39
    - readline 8.1 h46c0cb4_0
    - setuptools 49.6.0 py39hf3d152e_3
    - sqlite 3.35.5 h74cdb3f_0
    - tk 8.6.10 h21135ba_1
    - tzdata 2021a he74cb21_0
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - click >=7.1.2
    - itsdangerous >=2.0
    - jinja2 >=3.0
    - python >=3.6
    - werkzeug >=2.0
test:
  commands:
    - flask --help
    - pip check
  imports:
    - flask
    - flask.json
  requires:
    - pip
about:
  description: 'Flask is a microframework for Python based on Werkzeug and Jinja2.
    It''s

    intended for getting started very quickly and was developed with best

    intentions in mind.

    '
  dev_url: https://github.com/pallets/flask
  doc_source_url: https://github.com/pallets/flask/blob/master/docs/index.rst
  doc_url: http://flask.pocoo.org/docs/1.0/
  home: http://flask.pocoo.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A microframework based on Werkzeug, Jinja2 and good intentions.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - goanpeca
    - marcelotrevisani
    - nehaljwani
    - ukaratay
    - xylar
