# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu Jun  3 19:23:39 2021
# ------------------------------------------------

package:
  name: typing_extensions
  version: 3.10.0.0
source:
  sha256: 50b6f157849174217d0656f99dc82fe932884fb250826c18350e159ec6cdf342
  url: https://pypi.io/packages/source/t/typing_extensions/typing_extensions-3.10.0.0.tar.gz
build:
  noarch: python
  number: '0'
  script: python -m pip install --no-deps --ignore-installed .
  string: pyha770c72_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.5.30 ha878542_0
    - certifi 2021.5.30 py39hf3d152e_0
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - libstdcxx-ng 9.3.0 h6de172a_19
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - pip 21.1.2 pyhd8ed1ab_0
    - python 3.9.4 hffdb5ce_0_cpython
    - python_abi 3.9 1_cp39
    - readline 8.1 h46c0cb4_0
    - setuptools 49.6.0 py39hf3d152e_3
    - sqlite 3.35.5 h74cdb3f_0
    - tk 8.6.10 h21135ba_1
    - tzdata 2021a he74cb21_0
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - python >=3.5
about:
  description: 'The typing module was added to the standard library in Python 3.5
    on a

    provisional basis and will no longer be provisional in Python 3.7. However,

    this means users of Python 3.5 - 3.6 who are unable to upgrade will not be

    able to take advantage of new types added to the typing module, such as

    typing.Text or typing.Coroutine.


    The typing_extensions module contains both backports of these changes

    as well as experimental types that will eventually be added to the typing

    module, such as Protocol.


    Users of other Python versions should continue to install and use the

    typing module from PyPi instead of using this one unless specifically

    writing code that must be compatible with multiple Python versions or

    requires experimental types.

    '
  dev_url: https://github.com/python/typing
  doc_url: https://github.com/python/typing
  home: https://github.com/python/typing/tree/master/typing_extensions
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  summary: Backported and Experimental Type Hints for Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - djsutherland
    - synapticarbors
