# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri May  7 11:44:38 2021
# ------------------------------------------------

package:
  name: attrs
  version: 21.2.0
source:
  fn: attrs-21.2.0.tar.gz
  sha256: ef6aaac3ca6cd92904cdd0d83f629a15f18053ec84e6432106f7a4d04ae4f5fb
  url: https://pypi.io/packages/source/a/attrs/attrs-21.2.0.tar.gz
build:
  noarch: python
  number: '0'
  script: python -m pip install . --no-deps --ignore-installed
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2020.12.5 ha878542_0
    - certifi 2020.12.5 py39hf3d152e_1
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - libstdcxx-ng 9.3.0 h6de172a_19
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - pip 21.1.1 pyhd8ed1ab_0
    - python 3.9.2 hffdb5ce_0_cpython
    - python_abi 3.9 1_cp39
    - readline 8.1 h46c0cb4_0
    - setuptools 49.6.0 py39hf3d152e_3
    - sqlite 3.35.5 h74cdb3f_0
    - tk 8.6.10 h21135ba_1
    - tzdata 2021a he74cb21_0
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*
test:
  imports:
    - attr
  requires:
    - coverage
    - hypothesis
    - pympler
    - six
    - zope
    - zope.interface
about:
  description: 'attrs is the Python package that will bring back the joy of writing

    classes by relieving you from the drudgery of implementing object

    protocols (aka dunder methods). Its main goal is to help you to write

    concise and correct software without slowing down your code. For that, it

    gives you a class decorator and a way to declaratively define the

    attributes on that class:

    '
  dev_url: https://github.com/python-attrs/attrs
  doc_url: https://attrs.readthedocs.io/en/stable/
  home: https://attrs.readthedocs.io/en/stable/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: attrs is the Python package that will bring back the joy of writing classes
    by relieving you from the drudgery of implementing object protocols (aka dunder
    methods).
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - CJ-Wright
    - jochym
    - licode
    - nicoddemus
