# This file created by conda-build 3.21.4
# ------------------------------------------------

package:
  name: glib
  version: 2.68.4
source:
  patches:
    - hardcoded-paths.patch
    - skip-gio-tests-meson.build.patch
    - skip-gio-tests-resources.c.patch
    - skip-glib-tests-fileutils.c.patch
  sha256: 62fd061d08a75492617e625a73e2c05e259f831acbb8e1f8b9c81f23f7993a3b
  url: https://download.gnome.org/sources/glib/2.68/glib-2.68.4.tar.xz
build:
  ignore_run_exports_from:
    - python *
  number: 0
  run_exports:
    - libglib >=2.68.4,<3.0a0
  string: h9c3ff4c_0
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - binutils_impl_linux-64 2.36.1 h193b22a_2
    - binutils_linux-64 2.36 hf3e587d_0
    - ca-certificates 2021.5.30 ha878542_0
    - gcc_impl_linux-64 9.4.0 h03d3576_8
    - gcc_linux-64 9.4.0 h391b98a_0
    - gxx_impl_linux-64 9.4.0 h03d3576_8
    - gxx_linux-64 9.4.0 h0316aca_0
    - kernel-headers_linux-64 2.6.32 he073ed8_14
    - ld_impl_linux-64 2.36.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-devel_linux-64 9.4.0 hd854feb_8
    - libgcc-ng 11.1.0 hc902ee8_8
    - libgomp 11.1.0 hc902ee8_8
    - libsanitizer 9.4.0 h79bfe98_8
    - libstdcxx-devel_linux-64 9.4.0 hd854feb_8
    - libstdcxx-ng 11.1.0 h56837e0_8
    - meson 0.59.1 pyhd8ed1ab_0
    - ncurses 6.2 h58526e2_4
    - ninja 1.10.2 h4bd325d_0
    - openssl 1.1.1k h7f98852_1
    - pkg-config 0.29.2 h36c2ea0_1008
    - python 3.9.6 h49503c6_1_cpython
    - python_abi 3.9 2_cp39
    - readline 8.1 h46c0cb4_0
    - setuptools 57.4.0 py39hf3d152e_0
    - sqlite 3.36.0 h9cd32fc_0
    - sysroot_linux-64 2.12 he073ed8_14
    - tk 8.6.10 h21135ba_1
    - tzdata 2021a he74cb21_1
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - gettext 0.19.8.1 h0b5b191_1005
    - glib-tools 2.68.4 h9c3ff4c_0
    - libffi 3.3 h58526e2_2
    - libgcc-ng 11.1.0 hc902ee8_8
    - libglib 2.68.4 h3e27bee_0
    - libgomp 11.1.0 hc902ee8_8
    - libstdcxx-ng 11.1.0 h56837e0_8
  run:
    - gettext >=0.19.8.1,<1.0a0
    - glib-tools 2.68.4 h9c3ff4c_0
    - libgcc-ng >=9.4.0
    - libglib 2.68.4 h3e27bee_0
    - libstdcxx-ng >=9.4.0
    - python *
test:
  commands:
    - test -f ${PREFIX}/lib/libglib-2.0${SHLIB_EXT}
    - gapplication help
    - gdbus help
    - gobject-query --help
    - gresource help
    - gtester --help
about:
  home: https://developer.gnome.org/glib/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: Provides core application building blocks for libraries and applications
    written in C.
extra:
  copy_test_source_files: true
  feedstock-name: glib
  final: true
  recipe-maintainers:
    - ccordoba12
    - isuruf
    - jakirkham
    - ocefpaf
    - pkgw
    - scopatz
    - tschoonj
    - xhochy
