# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Tue Jun  1 22:21:36 2021
# ------------------------------------------------

package:
  name: prometheus_client
  version: 0.11.0
source:
  sha256: 68dad62135c7b58126e4a5c712de7459bcc7bb10338f8ac19f631e8873aefee3
  url: https://github.com/prometheus/client_python/archive/v0.11.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/prometheus_client_1622586138406/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2021.5.30 ha878542_0
    - certifi 2021.5.30 py39hf3d152e_0
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_19
    - libgomp 9.3.0 h2828fa1_19
    - libstdcxx-ng 9.3.0 h6de172a_19
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - pip 21.1.2 pyhd8ed1ab_0
    - python 3.9.4 hffdb5ce_0_cpython
    - python_abi 3.9 1_cp39
    - readline 8.1 h46c0cb4_0
    - setuptools 49.6.0 py39hf3d152e_3
    - sqlite 3.35.5 h74cdb3f_0
    - tk 8.6.10 h21135ba_1
    - tzdata 2021a he74cb21_0
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - python >=3.6
test:
  commands:
    - pip check
  imports:
    - prometheus_client
    - prometheus_client.bridge
  requires:
    - pip
about:
  home: https://github.com/prometheus/client_python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python client for the Prometheus monitoring system
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jessicaaustin
    - kwilcox
    - ocefpaf
