# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Wed Mar 31 00:01:17 2021
# ------------------------------------------------

package:
  name: parso
  version: 0.8.2
source:
  fn: parso-0.8.2.tar.gz
  sha256: 12b83492c6239ce32ff5eed6d3639d6a536170723c6f3f1506869f1ace413398
  url: https://pypi.io/packages/source/p/parso/parso-0.8.2.tar.gz
build:
  noarch: python
  number: '0'
  script: /home/conda/feedstock_root/build_artifacts/parso_1617148930513/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/bin/python
    -m pip install . -vv
  string: pyhd8ed1ab_0
requirements:
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 1_gnu
    - ca-certificates 2020.12.5 ha878542_0
    - certifi 2020.12.5 py39hf3d152e_1
    - ld_impl_linux-64 2.35.1 hea4e1c9_2
    - libffi 3.3 h58526e2_2
    - libgcc-ng 9.3.0 h2828fa1_18
    - libgomp 9.3.0 h2828fa1_18
    - libstdcxx-ng 9.3.0 h6de172a_18
    - ncurses 6.2 h58526e2_4
    - openssl 1.1.1k h7f98852_0
    - pip 21.0.1 pyhd8ed1ab_0
    - python 3.9.2 hffdb5ce_0_cpython
    - python_abi 3.9 1_cp39
    - readline 8.0 he28a2e2_2
    - setuptools 49.6.0 py39hf3d152e_3
    - sqlite 3.35.3 h74cdb3f_0
    - tk 8.6.10 h21135ba_1
    - tzdata 2021a he74cb21_0
    - wheel 0.36.2 pyhd3deb0d_0
    - xz 5.2.5 h516909a_1
    - zlib 1.2.11 h516909a_1010
  run:
    - python >=3.6
test:
  imports:
    - parso
    - parso.pgen2
    - parso.python
about:
  description: 'Parso is a Python parser that supports error recovery and round-trip
    parsing for different Python versions (in multiple Python versions).

    Parso is also able to list multiple syntax errors in your python file.

    '
  dev_url: https://github.com/davidhalter/parso
  doc_url: https://parso.readthedocs.io/en/latest/
  home: https://github.com/davidhalter/parso
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A Python Parser
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - iron0012
    - synapticarbors
